services:
  moodcreator:
    image: ghcr.io/danek309044/moodcreator:latest
    # build: .   # uncomment to build from source instead
    container_name: moodcreator
    ports:
      - "4444:4444"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - TZ=Europe/Prague